version: '3.5'

services:
  postgres_service:
    container_name: postgres_container
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=user1
    image: postgres:14.3-alpine


