spring:
  application:
   name=springbootG
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: user1
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true


